services:
  web:
    image: pcdiks/bmmanager:latest
    environment:
      - DEBUG=False
      - SECRET_KEY=my-very-secret-key
      - DB_NAME=/data/db.sqlite3
      - EMAIL_HOST=smtp.domain.com
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False
      - DEFAULT_FROM_EMAIL=bmmanager@domain.com
      - ALLOWED_HOSTS = ["bmmanager.domain.com"]
      - APP_HOST=bmmanager.domain.com
    volumes:
      - ./data:/data
    ports:
      - "80:80"